### PR TITLE
Feature/implement employee crud

### PR DESCRIPTION
**Pull request by goran-erhartic-devtech**
# What's the purpose of this MR?

This MR implements CRUD actions for Employee. 

# Impact Analysis

Added API routes for Employee CRUD operations

# Where should the tester start?

Follow the instructions below

# How should this be manually tested?

GET - '/employees' (returns all employees from DB)
GET - '/employee/{id}' (return employee by ID)
POST - '/employee' (create new employee: name(str)!, age(int)!, jmbg(int)!!, project(str), department(str), isActive(int)!)
PUT - '/employee/{id}' (edit employee with ID: name(str)!, age(int)!, jmbg(int)!!, project(str), department(str), isActive(int)!)
DELETE - '/employee/{id}' (delete employee by ID)

! required
!! required and unique

# Any background context you want to provide?
(N/A)

# What are the relevant tickets?

(N/A)

# Screenshots (if appropriate)

(N/A)

### CODE REVIEW

**Comment by dejan-babic** [comment]
@goran-erhartic-devtech 
You should consider having a unified JSON response for all actions. Typically the response would be similar to this : 
`
{
 success: true
 message: 'There are 2 users'
 data: [{user}, {user}]
}
`

There are some built in facilities in lumen, but nothing stops you to create a response object wrapper.

**Comment by goran-erhartic-devtech** [comment]
@dejan-babic Implemented recommended JSON response

**Comment by dejan-babic** [comment]
@goran-erhartic-devtech 
Better but... I want you to thing about this scenario: How would you set a fail case response with your class?
You have repetitive code ($out{...}) these could be class properties 
Are the methods public or?

**Comment by goran-erhartic-devtech** [comment]
@dejan-babic implemented recommended changes

**Pull request merged**
